// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YWkpDcSqUJQcicI2KH5cyYu7dLMEYqg',
    appId: '1:274973881702:web:52a3991d91b2d377d544a7',
    messagingSenderId: '274973881702',
    projectId: 'notes-app-931f0',
    authDomain: 'notes-app-931f0.firebaseapp.com',
    storageBucket: 'notes-app-931f0.firebasestorage.app',
    measurementId: 'G-C1QHJ98B5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYBv7xavc17D_ZAi9nHrG2zgdDVwUXrFg',
    appId: '1:274973881702:android:1f57d4b067870206d544a7',
    messagingSenderId: '274973881702',
    projectId: 'notes-app-931f0',
    storageBucket: 'notes-app-931f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqNpSSPvFkrOuXe-EhkJpMQp4IV_huow',
    appId: '1:274973881702:ios:aa6951c7a1bd1700d544a7',
    messagingSenderId: '274973881702',
    projectId: 'notes-app-931f0',
    storageBucket: 'notes-app-931f0.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqNpSSPvFkrOuXe-EhkJpMQp4IV_huow',
    appId: '1:274973881702:ios:aa6951c7a1bd1700d544a7',
    messagingSenderId: '274973881702',
    projectId: 'notes-app-931f0',
    storageBucket: 'notes-app-931f0.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-YWkpDcSqUJQcicI2KH5cyYu7dLMEYqg',
    appId: '1:274973881702:web:de79451660377fadd544a7',
    messagingSenderId: '274973881702',
    projectId: 'notes-app-931f0',
    authDomain: 'notes-app-931f0.firebaseapp.com',
    storageBucket: 'notes-app-931f0.firebasestorage.app',
    measurementId: 'G-59SWEHYEML',
  );

}